{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <testcase.test_pytest_object.TestPytestObject object at 0x10ba140f0>\n\n    @pytest.mark.run(order=1)\n    def test_two(self):\n>       assert 1==2\nE       assert 1 == 2\n\ntestcase/test_pytest_object.py:35: AssertionError"}, "attachments": [{"name": "log", "source": "054f79c1-afbc-4950-a9f0-a7eb808b8f39-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ce4dfa54-38c2-477b-bbab-fba2e5ce03b9-attachment.txt", "type": "text/plain"}], "start": 1574315562012, "stop": 1574315562013, "uuid": "0b94f214-4be5-4178-a2c1-f809b0e243de", "historyId": "e45a9f943edb368299f68c94931f54bc", "testCaseId": "b2cbcde5e1e96f90f4078670e3a822a6", "fullName": "testcase.test_pytest_object.TestPytestObject#test_two", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_pytest_object"}, {"name": "subSuite", "value": "TestPytestObject"}, {"name": "host", "value": "lvdeMacBook-Pro.local"}, {"name": "thread", "value": "61486-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_pytest_object"}]}