{"name": "test_one", "status": "failed", "statusDetails": {"message": "AssertionError: assert True == False", "trace": "self = <testcase.test_pytest_object.TestPytestObject object at 0x10ba14160>\n\n    @pytest.mark.run(order=2)\n    def test_one(self):\n>       assert  True==False\nE       assert True == False\n\ntestcase/test_pytest_object.py:39: AssertionError"}, "attachments": [{"name": "log", "source": "b56f2858-3c90-4fcf-a07e-76f0895056dc-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "dbfc7355-2f08-41dc-95c9-379b7cf0a271-attachment.txt", "type": "text/plain"}], "start": 1574315562066, "stop": 1574315562066, "uuid": "e85eaaf3-aa56-4421-8b7f-95958f2d7471", "historyId": "474d30c50d61b39677d5ec11f9b407d1", "testCaseId": "d52259a964a7a1ff3f35a6e17fbecd89", "fullName": "testcase.test_pytest_object.TestPytestObject#test_one", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_pytest_object"}, {"name": "subSuite", "value": "TestPytestObject"}, {"name": "host", "value": "lvdeMacBook-Pro.local"}, {"name": "thread", "value": "61486-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_pytest_object"}]}